[package]
name = "server"
version = "0.1.0"
edition = "2021"


[dependencies]
tracing.workspace = true

tracing-subscriber.workspace = true

tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

crush.workspace = true

[lints]
workspace = true
